# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logs_format.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tags_pb2 as tags__pb2
import data_entity_pb2 as data__entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='logs_format.proto',
  package='data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11logs_format.proto\x12\x04\x64\x61ta\x1a\ntags.proto\x1a\x11\x64\x61ta_entity.proto\"A\n\rEntityPiiList\x12\x30\n\x11\x65ntity_pii_record\x18\x01 \x03(\x0b\x32\x15.data.EntityPiiRecord\"]\n\x0f\x45ntityPiiRecord\x12&\n\x0craw_pii_item\x18\x01 \x03(\x0b\x32\x10.data.RawPiiItem\x12\"\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x11.data.FeatureItem\"\xa3\x01\n\x08PiiIeLog\x12\x0c\n\x04sha1\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12%\n\x08pii_list\x18\x03 \x03(\x0b\x32\x13.data.EntityPiiList\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\r\n\x05org_h\x18\x05 \x01(\t\x12\r\n\x05org_p\x18\x06 \x01(\t\x12\x0e\n\x06resp_h\x18\x07 \x01(\t\x12\x0e\n\x06resp_p\x18\x08 \x01(\t\"\x89\x01\n\x05\x46uzzy\x12\x0c\n\x04sha1\x18\x01 \x01(\t\x12\x17\n\x0forigin_filename\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x12\n\nfuzzy_hash\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x12\r\n\x05known\x18\x06 \x01(\x08\x12\x10\n\x08interest\x18\x07 \x01(\x08\"\x07\n\x05\x46iles\"\xbb\x01\n\x08\x46ileInfo\x12\x0c\n\x04sha1\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12#\n\x08log_type\x18\x04 \x01(\x0e\x32\x11.data.FileLogType\x12\x1e\n\x06pii_ie\x18\x05 \x01(\x0b\x32\x0e.data.PiiIeLog\x12\x1a\n\x05\x66uzzy\x18\x06 \x01(\x0b\x32\x0b.data.Fuzzy\x12\x1a\n\x05\x66iles\x18\x07 \x01(\x0b\x32\x0b.data.Filesb\x06proto3')
  ,
  dependencies=[tags__pb2.DESCRIPTOR,data__entity__pb2.DESCRIPTOR,])




_ENTITYPIILIST = _descriptor.Descriptor(
  name='EntityPiiList',
  full_name='data.EntityPiiList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_pii_record', full_name='data.EntityPiiList.entity_pii_record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=123,
)


_ENTITYPIIRECORD = _descriptor.Descriptor(
  name='EntityPiiRecord',
  full_name='data.EntityPiiRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_pii_item', full_name='data.EntityPiiRecord.raw_pii_item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='data.EntityPiiRecord.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=218,
)


_PIIIELOG = _descriptor.Descriptor(
  name='PiiIeLog',
  full_name='data.PiiIeLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha1', full_name='data.PiiIeLog.sha1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='data.PiiIeLog.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pii_list', full_name='data.PiiIeLog.pii_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.PiiIeLog.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org_h', full_name='data.PiiIeLog.org_h', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org_p', full_name='data.PiiIeLog.org_p', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resp_h', full_name='data.PiiIeLog.resp_h', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resp_p', full_name='data.PiiIeLog.resp_p', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=384,
)


_FUZZY = _descriptor.Descriptor(
  name='Fuzzy',
  full_name='data.Fuzzy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha1', full_name='data.Fuzzy.sha1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin_filename', full_name='data.Fuzzy.origin_filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='data.Fuzzy.file_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuzzy_hash', full_name='data.Fuzzy.fuzzy_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.Fuzzy.timestamp', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='known', full_name='data.Fuzzy.known', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interest', full_name='data.Fuzzy.interest', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=524,
)


_FILES = _descriptor.Descriptor(
  name='Files',
  full_name='data.Files',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=533,
)


_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='data.FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha1', full_name='data.FileInfo.sha1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.FileInfo.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='data.FileInfo.file_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_type', full_name='data.FileInfo.log_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pii_ie', full_name='data.FileInfo.pii_ie', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuzzy', full_name='data.FileInfo.fuzzy', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='data.FileInfo.files', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=723,
)

_ENTITYPIILIST.fields_by_name['entity_pii_record'].message_type = _ENTITYPIIRECORD
_ENTITYPIIRECORD.fields_by_name['raw_pii_item'].message_type = data__entity__pb2._RAWPIIITEM
_ENTITYPIIRECORD.fields_by_name['feature'].message_type = data__entity__pb2._FEATUREITEM
_PIIIELOG.fields_by_name['pii_list'].message_type = _ENTITYPIILIST
_FILEINFO.fields_by_name['log_type'].enum_type = tags__pb2._FILELOGTYPE
_FILEINFO.fields_by_name['pii_ie'].message_type = _PIIIELOG
_FILEINFO.fields_by_name['fuzzy'].message_type = _FUZZY
_FILEINFO.fields_by_name['files'].message_type = _FILES
DESCRIPTOR.message_types_by_name['EntityPiiList'] = _ENTITYPIILIST
DESCRIPTOR.message_types_by_name['EntityPiiRecord'] = _ENTITYPIIRECORD
DESCRIPTOR.message_types_by_name['PiiIeLog'] = _PIIIELOG
DESCRIPTOR.message_types_by_name['Fuzzy'] = _FUZZY
DESCRIPTOR.message_types_by_name['Files'] = _FILES
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntityPiiList = _reflection.GeneratedProtocolMessageType('EntityPiiList', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYPIILIST,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.EntityPiiList)
  ))
_sym_db.RegisterMessage(EntityPiiList)

EntityPiiRecord = _reflection.GeneratedProtocolMessageType('EntityPiiRecord', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYPIIRECORD,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.EntityPiiRecord)
  ))
_sym_db.RegisterMessage(EntityPiiRecord)

PiiIeLog = _reflection.GeneratedProtocolMessageType('PiiIeLog', (_message.Message,), dict(
  DESCRIPTOR = _PIIIELOG,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.PiiIeLog)
  ))
_sym_db.RegisterMessage(PiiIeLog)

Fuzzy = _reflection.GeneratedProtocolMessageType('Fuzzy', (_message.Message,), dict(
  DESCRIPTOR = _FUZZY,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.Fuzzy)
  ))
_sym_db.RegisterMessage(Fuzzy)

Files = _reflection.GeneratedProtocolMessageType('Files', (_message.Message,), dict(
  DESCRIPTOR = _FILES,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.Files)
  ))
_sym_db.RegisterMessage(Files)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), dict(
  DESCRIPTOR = _FILEINFO,
  __module__ = 'logs_format_pb2'
  # @@protoc_insertion_point(class_scope:data.FileInfo)
  ))
_sym_db.RegisterMessage(FileInfo)


# @@protoc_insertion_point(module_scope)
