# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scannerdata_locationinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tags_pb2 as tags__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scannerdata_locationinfo.proto',
  package='data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1escannerdata_locationinfo.proto\x12\x04\x64\x61ta\x1a\ntags.proto\"\x9b\x02\n\x0cLocationInfo\x12\x0b\n\x03Loc\x18\x01 \x01(\t\x12\x0e\n\x06Hashes\x18\x02 \x03(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0f\n\x07\x64\x62_name\x18\x05 \x01(\t\x12\x0f\n\x07\x66s_name\x18\x06 \x01(\t\x12\x12\n\ntable_name\x18\x07 \x01(\t\x12\x11\n\tfile_name\x18\x08 \x01(\t\x12\x10\n\x08\x63ol_name\x18\t \x01(\t\x12\x15\n\rnorm_col_name\x18\n \x01(\t\x12&\n\nfield_name\x18\x0b \x01(\x0e\x32\x12.data.PiiFieldName\x12\'\n\x0cstorage_type\x18\x0c \x01(\x0e\x32\x11.data.StorageType\x12\x11\n\ttimestamp\x18\r \x01(\x03\x62\x06proto3')
  ,
  dependencies=[tags__pb2.DESCRIPTOR,])




_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='data.LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Loc', full_name='data.LocationInfo.Loc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Hashes', full_name='data.LocationInfo.Hashes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='data.LocationInfo.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='data.LocationInfo.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db_name', full_name='data.LocationInfo.db_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fs_name', full_name='data.LocationInfo.fs_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='data.LocationInfo.table_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='data.LocationInfo.file_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='col_name', full_name='data.LocationInfo.col_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='norm_col_name', full_name='data.LocationInfo.norm_col_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='data.LocationInfo.field_name', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storage_type', full_name='data.LocationInfo.storage_type', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='data.LocationInfo.timestamp', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=336,
)

_LOCATIONINFO.fields_by_name['field_name'].enum_type = tags__pb2._PIIFIELDNAME
_LOCATIONINFO.fields_by_name['storage_type'].enum_type = tags__pb2._STORAGETYPE
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONINFO,
  __module__ = 'scannerdata_locationinfo_pb2'
  # @@protoc_insertion_point(class_scope:data.LocationInfo)
  ))
_sym_db.RegisterMessage(LocationInfo)


# @@protoc_insertion_point(module_scope)
