# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scannerdata_databasecatalog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tags_pb2 as tags__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scannerdata_databasecatalog.proto',
  package='data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!scannerdata_databasecatalog.proto\x12\x04\x64\x61ta\x1a\ntags.proto\"O\n\x06\x43olumn\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08\x44\x61taType\x18\x02 \x01(\t\x12\x16\n\x0eNormalizedName\x18\x03 \x01(\t\x12\r\n\x05Score\x18\x04 \x01(\x05\"7\n\x05Table\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12 \n\nColumnList\x18\x02 \x03(\x0b\x32\x0c.data.Column\"8\n\x08\x44\x61tabase\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x1e\n\tTableList\x18\x02 \x03(\x0b\x32\x0b.data.Table\"\x8e\x01\n\x0f\x44\x61taBaseCatalog\x12\x12\n\nSourceUUID\x18\x01 \x01(\t\x12\x0c\n\x04Host\x18\x02 \x01(\t\x12\x0c\n\x04Port\x18\x03 \x01(\x05\x12%\n\nStorageTyp\x18\x04 \x01(\x0e\x32\x11.data.StorageType\x12$\n\x0c\x44\x61tabaseList\x18\x05 \x03(\x0b\x32\x0e.data.Databaseb\x06proto3')
  ,
  dependencies=[tags__pb2.DESCRIPTOR,])




_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='data.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='data.Column.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DataType', full_name='data.Column.DataType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NormalizedName', full_name='data.Column.NormalizedName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Score', full_name='data.Column.Score', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=134,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='data.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='data.Table.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ColumnList', full_name='data.Table.ColumnList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=191,
)


_DATABASE = _descriptor.Descriptor(
  name='Database',
  full_name='data.Database',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='data.Database.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TableList', full_name='data.Database.TableList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=249,
)


_DATABASECATALOG = _descriptor.Descriptor(
  name='DataBaseCatalog',
  full_name='data.DataBaseCatalog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SourceUUID', full_name='data.DataBaseCatalog.SourceUUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Host', full_name='data.DataBaseCatalog.Host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Port', full_name='data.DataBaseCatalog.Port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StorageTyp', full_name='data.DataBaseCatalog.StorageTyp', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DatabaseList', full_name='data.DataBaseCatalog.DatabaseList', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=394,
)

_TABLE.fields_by_name['ColumnList'].message_type = _COLUMN
_DATABASE.fields_by_name['TableList'].message_type = _TABLE
_DATABASECATALOG.fields_by_name['StorageTyp'].enum_type = tags__pb2._STORAGETYPE
_DATABASECATALOG.fields_by_name['DatabaseList'].message_type = _DATABASE
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['Database'] = _DATABASE
DESCRIPTOR.message_types_by_name['DataBaseCatalog'] = _DATABASECATALOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
  DESCRIPTOR = _COLUMN,
  __module__ = 'scannerdata_databasecatalog_pb2'
  # @@protoc_insertion_point(class_scope:data.Column)
  ))
_sym_db.RegisterMessage(Column)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), dict(
  DESCRIPTOR = _TABLE,
  __module__ = 'scannerdata_databasecatalog_pb2'
  # @@protoc_insertion_point(class_scope:data.Table)
  ))
_sym_db.RegisterMessage(Table)

Database = _reflection.GeneratedProtocolMessageType('Database', (_message.Message,), dict(
  DESCRIPTOR = _DATABASE,
  __module__ = 'scannerdata_databasecatalog_pb2'
  # @@protoc_insertion_point(class_scope:data.Database)
  ))
_sym_db.RegisterMessage(Database)

DataBaseCatalog = _reflection.GeneratedProtocolMessageType('DataBaseCatalog', (_message.Message,), dict(
  DESCRIPTOR = _DATABASECATALOG,
  __module__ = 'scannerdata_databasecatalog_pb2'
  # @@protoc_insertion_point(class_scope:data.DataBaseCatalog)
  ))
_sym_db.RegisterMessage(DataBaseCatalog)


# @@protoc_insertion_point(module_scope)
